---
language: node_js
sudo: false
dist: trusty
node_js:
  - "10"

addons:
  chrome: stable

cache:
  yarn: true

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-data-2.7
  - EMBER_TRY_SCENARIO=ember-data-2.8
  - EMBER_TRY_SCENARIO=ember-data-2.10
  - EMBER_TRY_SCENARIO=ember-data-3.0
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
